### ISSUE TITLE
Incorrect display of the progress bar

### ISSUE THREAD

**Issue by Tsyklop** [AlexIIL/BetterLoadingScreen#24]
![default](https://cloud.githubusercontent.com/assets/6783568/8272178/8499bd34-1841-11e5-9c49-1d1a85d2114d.png)

**Comment by AlexIIL** [comment]
Hang on, what's happening here? Are you using a custom image file? (also i'm guessing thats 1.8?)

**Comment by Tsyklop** [comment]
@AlexIIL 1.7.10. I changed the file that comes by default.

**Comment by Tsyklop** [comment]
This occurs when the load reaches the "Reloading Resourse Packs"

**Comment by AlexIIL** [comment]
Does it look completely normal before? (Also can I have a look at the files you changed?)

**Comment by Tsyklop** [comment]
Prior to that it displayed normally and after too. 
This is a file that I changed. I took it from the archive BetterLoadingScreen and changed
![progressbars](https://cloud.githubusercontent.com/assets/6783568/8272242/dc697390-1843-11e5-9ad6-099313f1efcc.png)

**Comment by AlexIIL** [comment]
Its been kinda buggy for a while now when minecraft reloads the resource packs, but I will probably have to rewrite a potion of the rendering code to make it work :/

**Comment by AlexIIL** [comment]
Hmm, then that should work properly. That's pretty strange actually...

**Comment by Tsyklop** [comment]
I'll ask this question

**Comment by AlexIIL** [comment]
Ok, looks like this is an easier fix than I thought. Making a new jar now :)

**Comment by AlexIIL** [comment]
Fixed in 1.3.1

**Comment by AlexIIL** [comment]
(When they approve the file)

**Comment by Tsyklop** [comment]
thx.

**Comment by AlexIIL** [comment]
And they have approved the file. Could you verify that that does fix the issue you were having?

**Comment by Tsyklop** [comment]
The problem remains. Perhaps here the problem is that changing the length of the progress bar?

**Comment by Tsyklop** [comment]
default width:
![default](https://cloud.githubusercontent.com/assets/6783568/8272723/d10dcd4e-1856-11e5-9cae-b4996bdc8782.png)

I changed the width from 182 to 350.

**Comment by AlexIIL** [comment]
ooooh ok

**Comment by AlexIIL** [comment]
oh, now I am getting it.

**Comment by AlexIIL** [comment]
Silly me, assuming that the texture width would be the same size as whats displayed on screen. Ok, NOW its fixed

**Comment by AlexIIL** [comment]
Let me just clean up a few things like it...

**Comment by Tsyklop** [comment]
fixed. thx
